name: Deploy Nuget

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    env:
      PATH_SOLUTION: ./StringPlaceholder/StringPlaceholder.csproj
      PATH_SOLUTION_TESTS: ./Tests/Tests.csproj
      SOLUTION: ./StringPlaceholder.sln

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
          include-prerelease: true

      - name: Compile solution
        run: dotnet build ${{ env.SOLUTION }} --configuration Release

      - name: Execute tests
        run: dotnet test ${{ env.PATH_SOLUTION_TESTS }}  --verbosity minimal

      - name: Pack with dotnet
        run: dotnet pack ${{ env.PATH_SOLUTION }} --output nuget-packages --configuration Release

      - name: Push with dotnet
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
