name: Deploy Nuget com testes

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    env:
      CAMINHO_PROJETO: ./StringPlaceholder/StringPlaceholder.csproj
      CAMINHO_PROJETO_TESTES: ./Testes/Testes.csproj
      SOLUCAO: ./StringPlaceholder.sln

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"
          include-prerelease: true

      - name: Compile solution
        run: dotnet build ${{ env.SOLUCAO }} --configuration Release --no-restore

      - name: Execute tests
        run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} /p:Configuration=Release --no-restore --no-build --verbosity minimal

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
